services:
    production:
        build:
            context: .
            dockerfile: Dockerfile
        image: my-discord-app:prod
        command: node index.js
        volumes:
            - .:/usr/src/app
            - /usr/src/app/node_modules
        environment:
            - NODE_ENV=production
        develop:
            watch:
             - action: sync
               path: ./index.js
               target: /usr/src/app/index.js
             - action: rebuild
               path: ./package.json

    dev:
        build:
            context: .
            dockerfile: Dockerfile
        image: my-discord-app:dev
        command: node index.js
        volumes:
            - .:/usr/src/app
            - /usr/src/app/node_modules
        environment:
            - NODE_ENV=development
        restart: on-failure
        develop:
            watch:
             - action: sync
               path: ./index.js
               target: /usr/src/app/index.js
             - action: rebuild
               path: ./package.json

    deploy:
        build:
            context: .
            dockerfile: Dockerfile
        command: node deploy-commands.js
        develop:
            watch:
            - action: sync
              path: ./commands/slash/
              target: /usr/src/app/commands/slash