services:
    discord-bot:
        build:
            context: .
            dockerfile: Dockerfile
        image: my-discord-app
        command: node index.js
        volumes:
            - .:/usr/src/app
            - /usr/src/app/node_modules
        environment:
            - NODE_ENV=${NODE_ENV}
